"""Change lorry capacity to integer

Revision ID: 70c797e87a3a
Revises: a1a9e774b1e8
Create Date: 2025-11-28 19:27:27.384546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c797e87a3a'
down_revision = 'a1a9e774b1e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lorry_details', schema=None) as batch_op:
        batch_op.alter_column('capacity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lorry_details', schema=None) as batch_op:
        batch_op.alter_column('capacity',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
