"""Add Agreement model

Revision ID: 7ebe6e67d3d0
Revises: 80a15c4fb016
Create Date: 2025-11-25 19:51:20.811328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ebe6e67d3d0'
down_revision = '80a15c4fb016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agreement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loa_number', sa.String(length=100), nullable=False),
    sa.Column('total_mt_km', sa.Float(), nullable=False),
    sa.Column('rate_per_mt_km', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agreement')
    # ### end Alembic commands ###
