"""Add placement_date to Booking

Revision ID: a1a9e774b1e8
Revises: 489c9d699629
Create Date: 2025-11-28 17:27:52.798786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a9e774b1e8'
down_revision = '489c9d699629'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'placement_date',
                sa.Date(),
                nullable=False,
                server_default=sa.text("DATE('now')")
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('placement_date')

    # ### end Alembic commands ###
