"""Add soft delete fields to Booking

Revision ID: b0de50be2fde
Revises: ab31335f7198
Create Date: 2025-12-05 04:25:53.657341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0de50be2fde'
down_revision = 'ab31335f7198'
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Add as nullable with server_default so SQLite is happy
    with op.batch_alter_table("booking", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status",
                sa.String(length=20),
                nullable=True,
                server_default="ACTIVE"
            )
        )
        batch_op.add_column(sa.Column("cancelled_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("cancel_reason", sa.String(length=255), nullable=True))

    # Step 2: Backfill all existing rows
    op.execute("UPDATE booking SET status='ACTIVE' WHERE status IS NULL")

    # Step 3: Remove server_default + make NOT NULL
    with op.batch_alter_table("booking", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.String(length=20),
            nullable=False,
            server_default=None
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_status'))
        batch_op.drop_column('cancel_reason')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
