"""Add letter support and agreement placement ref

Revision ID: b445b4bb9ab1
Revises: 1043b4a75d07
Create Date: 2025-12-18 14:02:29.491453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b445b4bb9ab1'
down_revision = '1043b4a75d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_letter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('letter_type', sa.String(length=20), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('letter_date', sa.Date(), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('pdf_path', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_letter_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_letter_id', sa.Integer(), nullable=False),
    sa.Column('stored_path', sa.String(length=300), nullable=False),
    sa.Column('original_filename', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['booking_letter_id'], ['booking_letter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agreement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placement_ref_prefix', sa.String(length=150), nullable=True))

    with op.batch_alter_table('booking_material', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_material_to_booking_authority_id'), ['to_booking_authority_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_material', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_material_to_booking_authority_id'))

    with op.batch_alter_table('agreement', schema=None) as batch_op:
        batch_op.drop_column('placement_ref_prefix')

    op.drop_table('booking_letter_attachment')
    op.drop_table('booking_letter')
    # ### end Alembic commands ###
