"""Add LorryDetails model

Revision ID: fbfc1f075501
Revises: 7ebe6e67d3d0
Create Date: 2025-11-25 21:14:44.180325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbfc1f075501'
down_revision = '7ebe6e67d3d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lorry_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.String(length=50), nullable=False),
    sa.Column('carrier_size', sa.String(length=50), nullable=False),
    sa.Column('number_of_wheels', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lorry_details')
    # ### end Alembic commands ###
